@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueStudentList

UniqueStudentList -down-> Student


AddressBook *-[hidden]down->  Name

Student *--> "studentName" Name
Student *--> " parentName" Name
Student *-[hidden]-> Name
Student *-[hidden]-> Name
Student *-[hidden]-> Name
Student *--> StudentId
Student *--> Phone
Student *--> Email
Student *--> Address
Student *-right-> Attendance
Attendance -[hidden]- Address
@enduml
